[package]
name = "tfhers_cml"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8"
serde = "1.0.210"
serde_json = "1.0.128"

tfhe = { version = "0.7.1", features = ["integer"] }

[target.aarch64-apple-darwin.dependencies]
tfhe = { version = "0.7.1", features = ["integer", "aarch64-unix"] }

[target.x86_64-unknown-linux-gnu.dependencies]
tfhe = { version = "0.7.1", features = ["integer", "x86_64-unix"] }

[target.aarch64-unknown-linux-gnu.dependencies]
tfhe = { version = "0.7.1", features = ["integer", "aarch64-unix"] }

[target.x86_64-pc-windows-gnu.dependencies]
tfhe = { version = "0.7.1", features = ["integer", "x86_64"] }
