[package]
name = "tfhers_cml"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8"


tfhe = { version = "0.8.0", features = ["integer"] }

[target.x86_64-unknown-linux-gnu.dependencies]
tfhe = { version = "0.8.0", features = ["integer", "x86_64-unix"] }

[target.aarch64-unknown-linux-gnu.dependencies]
tfhe = { version = "0.8.0", features = ["integer", "aarch64-unix"] }

[target.x86_64-pc-windows-gnu.dependencies]
tfhe = { version = "0.8.0", features = ["integer", "aarch64-unix"] }

