name: check action compliance

on:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches:
      - main
      - 'release/*'

jobs:
  action-pin:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0901cf7b71c7ea6261ec69a3dc2bd3f9264f893e # v3.0.12
        with:
          allowlist: |
            slsa-framework/slsa-github-generator

  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: check-missing-teardown
        run: .github/workflows/scripts/teardown-check.sh
      - name: actionlint
        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821 # v2.0.0
